namespace WebApp.Client.Models;

public sealed record ArchiveItemDto(
    string Id,
    string Name,
    ArchiveItemKind Kind,
    string? Extension,
    long? SizeBytes,
    DateTime LastWriteTimeUtc,
    bool IsVideo,
    ThumbnailState ThumbnailState = ThumbnailState.Unavailable,
    string? ThumbnailUrl = null,
    HoverPreviewState HoverPreviewState = HoverPreviewState.Unavailable,
    string? HoverPreviewUrl = null,
    SubtitleState SubtitleState = SubtitleState.Unavailable,
    string? SubtitleUrl = null,
    double? DurationSeconds = null,
    int? Width = null,
    int? Height = null,
    bool IsMusic = false,
    string? AudioUrl = null,
    string? AlbumCoverUrl = null,
    bool IsImage = false,
    string? ImageUrl = null,
    bool IsBook = false,
    string? BookCoverUrl = null,
    string? BookTitle = null,
    string? BookAuthor = null,
    bool IsTextDocument = false,
    bool IsPdfDocument = false,
    string? PdfUrl = null,
    bool HasPlayableMedia = false);
